// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA74LuxbJlIfsH-YdrlkA0GrqtcIsuNyCU',
    appId: '1:513108174884:web:ac23735bb2755b9508d0b1',
    messagingSenderId: '513108174884',
    projectId: 'mohamed-saleh-b6ac9',
    authDomain: 'mohamed-saleh-b6ac9.firebaseapp.com',
    storageBucket: 'mohamed-saleh-b6ac9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi37a4wNKAklZSLjm-vWwZMor3QNOo8zo',
    appId: '1:513108174884:android:0a9c7f1159f910dc08d0b1',
    messagingSenderId: '513108174884',
    projectId: 'mohamed-saleh-b6ac9',
    storageBucket: 'mohamed-saleh-b6ac9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsGayRtgCKFHSadSKr4ZNgjNdn-JqQAIw',
    appId: '1:513108174884:ios:29007ff5a731c0ed08d0b1',
    messagingSenderId: '513108174884',
    projectId: 'mohamed-saleh-b6ac9',
    storageBucket: 'mohamed-saleh-b6ac9.appspot.com',
    iosBundleId: 'com.example.gradproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsGayRtgCKFHSadSKr4ZNgjNdn-JqQAIw',
    appId: '1:513108174884:ios:29007ff5a731c0ed08d0b1',
    messagingSenderId: '513108174884',
    projectId: 'mohamed-saleh-b6ac9',
    storageBucket: 'mohamed-saleh-b6ac9.appspot.com',
    iosBundleId: 'com.example.gradproj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA74LuxbJlIfsH-YdrlkA0GrqtcIsuNyCU',
    appId: '1:513108174884:web:268a8f5aa190d19608d0b1',
    messagingSenderId: '513108174884',
    projectId: 'mohamed-saleh-b6ac9',
    authDomain: 'mohamed-saleh-b6ac9.firebaseapp.com',
    storageBucket: 'mohamed-saleh-b6ac9.appspot.com',
  );

}